# Generated by Django 3.1.2 on 2020-12-31 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201230_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='is_followed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
