# Generated by Django 3.1.2 on 2020-12-05 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('TXT', 'Text'), ('Q', 'Quote'), ('IMG', 'Image'), ('VID', 'Video'), ('GIF', 'GIF'), ('AUD', 'Audio')], default='TXT', max_length=3)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='post/videos/')),
                ('gif', models.FileField(blank=True, null=True, upload_to='post/gifs/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='post/audio/')),
                ('is_reblogged', models.BooleanField(blank=True, default=False)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.note')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
