# Generated by Django 3.1.2 on 2020-12-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201205_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.note'),
        ),
    ]
