# Generated by Django 3.1.2 on 2020-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20201206_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
