# Generated by Django 3.1.2 on 2020-12-27 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20201221_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reblogs',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='post.post'),
        ),
        migrations.AlterField(
            model_name='reblogs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reblogged_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
