# Generated by Django 3.1.2 on 2020-12-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20201227_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reblogs',
            old_name='post',
            new_name='parent_post',
        ),
        migrations.RenameField(
            model_name='reblogs',
            old_name='user',
            new_name='reblogged_from',
        ),
    ]
