# Generated by Django 3.1.2 on 2020-12-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201227_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reblogs',
            old_name='reblogged_from',
            new_name='reblogger',
        ),
    ]
