# Generated by Django 3.1.2 on 2020-12-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20201227_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='quote_text',
            field=models.TextField(blank=True),
        ),
    ]
