# Generated by Django 3.1.2 on 2020-12-31 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0017_auto_20201231_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', through='post.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='notes',
            field=models.ManyToManyField(related_name='post_noted', through='post.Note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='reblogs',
            field=models.ManyToManyField(related_name='reblogged_posts', through='post.Reblog', to=settings.AUTH_USER_MODEL),
        ),
    ]
