# Generated by Django 3.1.2 on 2021-01-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20201231_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reblog',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='post.post'),
        ),
    ]
