# Generated by Django 3.1.2 on 2021-01-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0020_auto_20210101_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reblog',
            name='reblogged_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
